/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_haslo_excelregistermapcontrolboard_NativeProcessing_NativeWrapper */

#ifndef _Included_co_haslo_excelregistermapcontrolboard_NativeProcessing_NativeWrapper
#define _Included_co_haslo_excelregistermapcontrolboard_NativeProcessing_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_haslo_excelregistermapcontrolboard_NativeProcessing_NativeWrapper
 * Method:    nativeByteToIntArray
 * Signature: ([B)[I
 */
JNIEXPORT jintArray JNICALL Java_co_haslo_excelregistermapcontrolboard_NativeProcessing_NativeWrapper_nativeByteToIntArray
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     co_haslo_excelregistermapcontrolboard_NativeProcessing_NativeWrapper
 * Method:    nativeImaging
 * Signature: ([B)[I
 */
JNIEXPORT jintArray JNICALL Java_co_haslo_excelregistermapcontrolboard_NativeProcessing_NativeWrapper_nativeImaging
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
